[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fuse = "rtacvJhGMzaCHjAgscGQgQSZBveyP7jgzRkjSztoEd6"

[programs.devnet]
fuse = "rtacvJhGMzaCHjAgscGQgQSZBveyP7jgzRkjSztoEd6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/PsoZSQhHg7USeEx8qQLKNhjXARH1XBUj8iGDNp5Y22V.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
